### ISSUE TITLE
Difference between regions

### ISSUE THREAD

**Issue by bertroode** [dexcomapp/dexcomapp#13]
In the 2.4 folder there are versions for region1, region2 and region3.
What is the difference between these versions?

**Comment by Arakon** [comment]
As the rest of the filename says, one is for people who use mg/dL, one is for people who measure in mmol.

**Comment by bertroode** [comment]
Well thanks but I meant the difference between the regions. For instance in region 2 there is no version for mmol/l. So can or should I user version 3 or what should I do?
