### ISSUE TITLE
no com.dexcom.g6.region2.mmol-patched.apk in the folder

### ISSUE THREAD

**Issue by bertroode** [dexcomapp/dexcomapp#15]
There is no com.dexcom.g6.region2.mmoll-patched.apkavailable in the folder.
Is there a specific reason why it is not prsent?

**Comment by chaosbiber** [comment]
I believe this is because the region2/mmol doesn't exist? If I search the app in the PlayStore I get the links to region3. Changing the url manually, the region 2 version for mg/dl does exist, but the one with mmol doesn't.
