### ISSUE TITLE
[2.4] com.dexcom.g6.region1.mmol-patched.apk no longer providing data to AAPS

### ISSUE THREAD

**Issue by twain47** [dexcomapp/dexcomapp#16]
After ~ 7 days operating without problems AAPS stopped receiving BG data. The patched dexcom app itself continues to receive BG data. AndroidAPS has a 'CGM' button but the 'calibrate' button has disappeared. Android brought up a 'This app keeps stopping' message.

A phone restart made no difference. Removing the Patched Dexcom app completely and reinstalling and restarting the sensor caused everything to start working again.

The only unusual thing that had happened (about 20 minutes before the data stopped) was that we had briefly triggered the 'HIGH' message in dexcom.

Happy to provide logs but not sure what would be relevant to this.

**Comment by T1Diab** [comment]
New user to this App and am getting the same. Luckily I can have a get around by using xDrip+ get its data from Share and then broadcasting it into AAPS.

**Comment by twain47** [comment]
This reoccurred. No HIGH this time so probably not related to that.

**Comment by twain47** [comment]
And reoccurred again

**Comment by twain47** [comment]
Looks to be same issue as #19
